$( document ).ready(function() {
    console.log( "ready!" );
    var content = $("#answers");
   // content.append("<h3>hahaha</h3>");
    var text="";
    var countriesArray = $.map(countries, function (value, key) { return { value: value, data: key }; });
    
    //edit answer
    var answer=[];
/*    for(var i=0; i<14; i++){
    	answer[i]="<h1>aaaaaaaaaaaaaaa</h1>";
    	answer[i]+="<h1>aaaaaaaaaaaaaaa</h1>";
answer[i]+="<h1>aaaaaaaaaaaaaaa</h1>";
answer[i]+="<h1>aaaaaaaaaaaaaaa</h1>";
answer[i]+="<h1>aaaaaaaaaaaaaaa</h1>";
answer[i]+="<h1>aaaaaaaaaaaaaaa</h1>";
answer[i]+="<h1>aaaaaaaaaaaaaaa</h1>";
answer[i]+="<h1>aaaaaaaaaaaaaaa</h1>";
    	
    	}*/
    answer[0]="";
answer[0] += "         	<div id=\"answer1\"  class=\"col-lg-8\">";
answer[0] += "                    		<p>In each experiment there are tables and figures listed along with the experiment. In the figure you will find the Plot button. Click on the Plot button will help you plot the data you have. Please be aware that befor plotting you should follow three steps to get the data ready: <\/p>";
answer[0] += "                    		<ol>";
answer[0] += "                    			<li>Follow the instructions of each experiment to get the correct data;<\/li>";
answer[0] += "                    			<li>Fill all the data to the table untill all the cells of the table is reached;<\/li>";
answer[0] += "                    			<li>Make sure the button you click is paired with the table you've finished.<\/li>";
answer[0] += "                    		<\/ol>";
answer[0] += "                    		<p>Following is the figure showing the \"Plot\" button of a figure:<\/p>";
answer[0] += "                    		<img src=\"images\/tutor\/answer1.JPG\"><\/img>";
answer[0] += "                    	<\/div>";


answer[1]="";
answer[1] += "<div id=\"answer2\"  class=\"col-lg-8\">";
answer[1] += "                    		<p>To connect a circuit there are four steps you can follow:<\/p>";
answer[1] += "                    		<ol>";
answer[1] += "                    			<li>Locate the circuit board in each experiment. The location may vary;<\/li>";
answer[1] += "                    			<li>Find the circuit schematic in the instruction block, identify each component on the schematic;<\/li>";
answer[1] += "                    			<li>Click the area between two dots on the circuit board and then select the correct component according to the circuit schematic;<\/li>";
answer[1] += "                    			<li>Live instructions at the left corner of the circuit board will show you if a circuit is connected correctly.<\/li>";
answer[1] += "                    		<\/ol>";
answer[1] += "                    		<p>Hint: If you connect the circuit incorrectly, you can click again on the component and choose to whether disconnect it or change the component.<\/p>";
answer[1] += "                    		<p>Following is the figure showing exaple of connecting a circuit:<\/p>";
answer[1] += "                    		<img src=\"images\/tutor\/answer2.jpg\"><\/img>";
answer[1] += "                    	<\/div>";

answer[2]="";
answer[2] += "<div id=\"answer3\"  class=\"col-lg-8\">";
answer[2] += "                    		<p>To view the records of the students please click the button (4) in the following figure:<\/p>";
answer[2] += "                    		<img src=\"images\/tutor\/answer31.jpg\"><\/img>";
answer[2] += "                    		<p>You have to select “User Managements”->”Grade Center”. You will see a list of all the records as shown below:<\/p>";
answer[2] += "                    		<img src=\"images\/tutor\/answer32.jpg\"><\/img>";
answer[2] += "                    		<p>Click on “submit time” column twice, the most recent record will be shown at the first row, please click “Grade it” if you want to view the record.<\/p>";
answer[2] += "                    ";
answer[2] += "                    		";
answer[2] += "                    	<\/div>";

answer[3]="";
answer[3] += "	<div id=\"answer4\"  class=\"col-lg-8\">";
answer[3] += "                    		<p>To start learning the power concepts, please click button (2) in the following figure To start the experiments, please click button (3) to begin the first experiment. It’s recommended to go through the learning material before attempting the experiments. <\/p>";
answer[3] += "							<img src=\"images\/tutor\/answer31.jpg\"><\/img>";
answer[3] += "							<p>A screenshot of the power concept page is shown below, follow the numerical order in the figure below:<\/p>";
answer[3] += "							<img src=\"images\/tutor\/answer4.jpg\"><\/img>";
answer[3] += "                    		";
answer[3] += "                    		";
answer[3] += "                    	<\/div>";


answer[4]="";
answer[4] += "<div id=\"answer5\"  class=\"col-lg-8\">";
answer[4] += "                    		<p>Once finished with all of the knowledge base material, you will be redirected to an experiment concept page. It’s similar in content to the power concept page and can be seen in figure below:<\/p>";
answer[4] += "							<img src=\"images\/tutor\/answer5.jpg\"><\/img>";
answer[4] += "				";
answer[4] += "                    		";
answer[4] += "                    		";
answer[4] += "                    	<\/div>";
answer[4] += "                    	";


answer[5]="";
answer[5] += "<div id=\"answer6\"  class=\"col-lg-8\">";
answer[5] += "                    		<p>The Instructions for experiment 1 are shown below:<\/p>";
answer[5] += "                    				<ol>";
answer[5] += "													<li>";
answer[5] += "														Connect the circuit according to the schematic diagram.";
answer[5] += "													<\/li>";
answer[5] += "													<li>";
answer[5] += "														Once the circuit is connected correctly, set the speed of the turbine to \"1800 rpm\" by clicking the \"+\" button. Then turn on the generator by clicking the switch button.";
answer[5] += "													<\/li>";
answer[5] += "													<li>";
answer[5] += "														Read the voltage value when the current is \"0.0 A\", then fill this value into the table.";
answer[5] += "													<\/li>";
answer[5] += "													<li>";
answer[5] += "														Decrease the field resistance by clicking the \"-\" button of the left Rheostat, thus increasing the field current. Read the current values in steps of 0.1 A and fill these values into the table. Then turn off the generator.";
answer[5] += "													<\/li>";
answer[5] += "												<\/ol>";
answer[5] += "				";
answer[5] += "                    		";
answer[5] += "                    		";
answer[5] += "                    	<\/div>";


answer[6]="";
answer[6] += "<div id=\"answer7\"  class=\"col-lg-8\">";
answer[6] += "                    		<p>The Instructions for experiment 2 are shown below:<\/p>";
answer[6] += "                    				";
answer[6] += "										<ol>";
answer[6] += "												<li>";
answer[6] += "													Connect the circuit according to the schematic diagram below.";
answer[6] += "												<\/li>";
answer[6] += "												<li>";
answer[6] += "													Once the circuit is connected correctly, set the rheostat to 100 Ohm: click on the rheostat and select \"Change Resistor Value\" option and then drag the slider to select the correct resistance value.";
answer[6] += "												<\/li>";
answer[6] += "												<li>";
answer[6] += "													Set the turbine speed to \"1800 rpm\", then click on the switch to turn on the generator. If anything is wrong in the above steps, the generator won't start. You should fix the errors following the pop up messages.";
answer[6] += "												<\/li>";
answer[6] += "												<li>";
answer[6] += "													Once the generator is started, its terminal voltage will quickly rise and settle to a constant value.  This voltage buildup process is typical for any DC shunt  generator. In this experiment, the voltage data is automatically recorded and plotted.";
answer[6] += "												<\/li>";
answer[6] += "												<li>";
answer[6] += "													Fill up the table with calculated voltage according to equation E=I*R. Here I is the field current and R is the field resistance.";
answer[6] += "												<\/li>";
answer[6] += "												<li>";
answer[6] += "													Click the \"plot\" button in the figure to draw the \"Calculated Voltage\" line. Then answer the questions in the last section.";
answer[6] += "												<\/li>";
answer[6] += "												<li>";
answer[6] += "													Click the \"Save Data & Proceed\" button to save the data.";
answer[6] += "												<\/li>";
answer[6] += "												<li>";
answer[6] += "													Turn off the generator.";
answer[6] += "												<\/li>";
answer[6] += "											<\/ol>";
answer[6] += "                    		";
answer[6] += "                    		";
answer[6] += "                    	<\/div>";


answer[7]="";
answer[7] += "<div id=\"answer8\"  class=\"col-lg-8\">";
answer[7] += "                    		<p>The Instructions for experiment 3 are shown below:<\/p>";
answer[7] += "                    				<ul>";
answer[7] += "															<li>";
answer[7] += "																Part 1: Start the generator.";
answer[7] += "																<ol>";
answer[7] += "																	<li>";
answer[7] += "																		Connect the generator as shown in the schematic.  Set the prime mover speed to 1800 rpm.";
answer[7] += "																	<\/li>";
answer[7] += "																	<li>";
answer[7] += "																		Turn on the generator by clicking the switch.  The voltmeter connected to the generator terminals should show a small voltage due to residual magnetism.";
answer[7] += "";
answer[7] += "																	<\/li>";
answer[7] += "																	<li>";
answer[7] += "																		Adjust the field rheostat by clicking +\/- buttons until the generator terminal voltage rises to approximately 120V.";
answer[7] += "																	<\/li>";
answer[7] += "																<\/ol>";
answer[7] += "														<\/ul>";
answer[7] += "														<ul>";
answer[7] += "															<li>";
answer[7] += "																Part 2: Load Voltage Build-up.";
answer[7] += "																<ol>";
answer[7] += "																	<li>";
answer[7] += "																		Load the generator by varying the load resistance.  Click on the +\/- buttons to vary the load rheostat.  For each step, record the load current, terminal voltage, and the generator field current.  Then shut down the generator.";
answer[7] += "																	<\/li>";
answer[7] += "																	<li>";
answer[7] += "																		For each value of the load current, calculate the terminal voltage using the generator circuit model (Note that Armature Resistance is 1 Ohm).  Enter the data in the table.";
answer[7] += "																	<\/li>";
answer[7] += "																<\/ol>";
answer[7] += "															<\/li>";
answer[7] += "														<\/ul>";
answer[7] += "				";
answer[7] += "                    		";
answer[7] += "                    		";
answer[7] += "                    	<\/div>";


answer[8]="";
answer[8] += "<div id=\"answer9\"  class=\"col-lg-8\">";
answer[8] += "                    		<p>The Instructions for experiment 4 are shown below:<\/p>";
answer[8] += "                    											<ol>";
answer[8] += "												<li>";
answer[8] += "													Once the circuit is connected correctly, set the prime mover speed at 1800 rpm. Keep the load terminal open. Measure the generator terminal voltage.";
answer[8] += "												<\/li>";
answer[8] += "												<li>";
answer[8] += "";
answer[8] += "													Switch on the load circuit.  Vary the load current from 0 to 5A in steps of 0.5A (click on \"-\" untill it reaches the lowest).  For each step, record the field current.";
answer[8] += "												<\/li>";
answer[8] += "												<li>";
answer[8] += "													For each value of the load current, calculate the terminal voltage by solving the generator circuit model.  Plot the calculated terminal voltage and the actual terminal voltage as a function of the load current.";
answer[8] += "												<\/li>";
answer[8] += "											<\/ol>";
answer[8] += "				";
answer[8] += "                    		";
answer[8] += "                    		";
answer[8] += "                    	<\/div>";

answer[9]="";
answer[9] += "<div id=\"answer10\"  class=\"col-lg-8\">";
answer[9] += "                    		<p>The Instructions for experiment 5 are shown below:<\/p>";
answer[9] += "                    			<ul>";
answer[9] += "														<li>";
answer[9] += "															Part 1: Rheostat Startup.";
answer[9] += "															<ol>";
answer[9] += "																<li>";
answer[9] += "																	Connect the circuit as shown in the schematic.  Set the prime mover speed at 1800 rpm.							<\/li>";
answer[9] += "																<li>";
answer[9] += "																	Turn on the generator by clicking the switch button. Set the shunt rheostat at zero resistance (click on \"-\" untill it reaches the lowest).";
answer[9] += "";
answer[9] += "																<\/li>";
answer[9] += "																<li>";
answer[9] += "																	The generator terminal voltage should increase to a voltage close to the rated voltage, Which is above 120 V. ";
answer[9] += "																<\/li>";
answer[9] += "															<\/ol>";
answer[9] += "													<\/ul>";
answer[9] += "													<ul>";
answer[9] += "														<li>";
answer[9] += "															Part 2: Load the generator.";
answer[9] += "															<ol>";
answer[9] += "																";
answer[9] += "";
answer[9] += "																<li>";
answer[9] += "																	Vary the load current from 0 to 5A in steps of 0.5A.  For each step, read the load current and the field current, and then fill them in the table.";
answer[9] += "																<\/li>";
answer[9] += "																<li>";
answer[9] += "																	For each value of load current, record the load voltage and the field current.";
answer[9] += "																		<\/li>";
answer[9] += "																		<li>";
answer[9] += "																			Use armature resistance of 1 ohm and the series field resistance of 0.1 ohm. Calculate the terminal voltage and record in the table. ";
answer[9] += "																		<\/li>";
answer[9] += "															<\/ol>";
answer[9] += "														<\/li>";
answer[9] += "													<\/ul>";
answer[9] += "				";
answer[9] += "                    		";
answer[9] += "                    		";
answer[9] += "                    	<\/div>";


answer[10]="";
answer[10] += "<div id=\"answer11\"  class=\"col-lg-8\">";
answer[10] += "                    		<p>The Instructions for experiment 6 are shown below:<\/p>";
answer[10] += "                    				<ol>";
answer[10] += "												<li>";
answer[10] += "";
answer[10] += "															Connect the circuit according to the schematic correctly.  Switch on the power supply and monitor the motor speed and the armature current.";
answer[10] += "														<\/li>";
answer[10] += "														<li>";
answer[10] += "															As the machine speeds up, cut down the starter resistance in several steps, typically about four to five steps.";
answer[10] += "														<\/li>";
answer[10] += "														<li>";
answer[10] += "															The motor assumes full speed in a few seconds, the data acquisition system automatically records the motor speed and the armature current which will be displayed on the computer monitor.";
answer[10] += "														<\/li>";
answer[10] += "														<li>";
answer[10] += "															Note the direction of rotation.  Shut down the motor.";
answer[10] += "														<\/li>";
answer[10] += "														";
answer[10] += "														";
answer[10] += "													<\/ol>";
answer[10] += "				";
answer[10] += "                    		";
answer[10] += "                    		";
answer[10] += "                    	<\/div>";

answer[11]="";
answer[11] += "<div id=\"answer12\"  class=\"col-lg-8\">";
answer[11] += "                    		<p>The Instructions for experiment 7 are shown below:<\/p>";
answer[11] += "                    				<ol>";
answer[11] += "														<li>";
answer[11] += "															Set the power supply to 120V dc.  Set the field resistance to the lowest value so that field current is maximum to produce a high starting torque.";
answer[11] += "														<\/li>";
answer[11] += "														<li>";
answer[11] += "															Set the starter resistance to the highest possible value.  Switch on the power supply and monitor the motor speed and the armature current.  The machine speeds up to about 1800 rpm in a few seconds.";
answer[11] += "														<\/li>";
answer[11] += "														<li>";
answer[11] += "															The motor is now running at full speed.  Now decrease the field current from 1.2A to a smaller value in steps of 0.1A.  For each step, note the machine speed; do not exceed 125% of the rated speed since a very high speed may damage the motor.  For each step, record the speed, armature current and the field current.   Shut down the motor as the speed reaches about 120% of rated value.";
answer[11] += "														<\/li>";
answer[11] += "														<li>";
answer[11] += "															Using the circuit model of the motor, calculate the motor speed for each field current. Fill in the table and plot the motor speed versus field current on the same figure as above.";
answer[11] += "														<\/li>";
answer[11] += "														<li>";
answer[11] += "															Also for each field current, calculate torque produced by the motor.";
answer[11] += "														<\/li>";
answer[11] += "													<\/ol>";
answer[11] += "				";
answer[11] += "                    		";
answer[11] += "                    		";
answer[11] += "                    	<\/div>";

answer[12]="";
answer[12] += "<div id=\"answer13\"  class=\"col-lg-8\">";
answer[12] += "                    		<p>The Instructions for experiment 8 are shown below:<\/p>";
answer[12] += "                    												<ol>";
answer[12] += "												<li>";
answer[12] += "													Set the power supply to 120V dc.  Set the field resistance to the lowest value so that field current is at a maximum to produce a high starting torque.";
answer[12] += "												<\/li>";
answer[12] += "												<li>";
answer[12] += "													Set the starter resistance to the highest possible value.  Switch on the power supply and monitor the motor speed and the armature current.  The machine speeds up to about 1800 rpm in a few seconds.";
answer[12] += "												<\/li>";
answer[12] += "												<li>";
answer[12] += "													The motor is now running at no load; in practice there is a small load due to friction at the shaft bearings.  Increase the mechanical load slowly from 0 to 0.45 Nm in steps of 0.05 Nm.  For each step, record the machine speed and armature current while keeping an eye on the motor current which must not exceed 120% of rated value.  Shut down the motor after experiment is completed.";
answer[12] += "												<\/li>";
answer[12] += "											<\/ol>";
answer[12] += "				";
answer[12] += "                    		";
answer[12] += "                    		";
answer[12] += "                    	<\/div>";

answer[13]="";
answer[13] += "<div id=\"answer14\"  class=\"col-lg-8\">";
answer[13] += "                    		<p>The Instructions for experiment 9 are shown below:<\/p>";
answer[13] += "                    													<ol>";
answer[13] += "													<li>";
answer[13] += "														Connect an ammeter and a starter resistance in series with the armature and the power supply.  ";
answer[13] += "													<\/li>";
answer[13] += "													<li>";
answer[13] += "";
answer[13] += "														Attach a tachometer to the machine shaft to monitor the motor speed.    ";
answer[13] += "													<\/li>";
answer[13] += " ";
answer[13] += "";
answer[13] += "												<\/ol>";
answer[13] += "				";
answer[13] += "                    		";
answer[13] += "                    		";
answer[13] += "                    	<\/div>";


    //end edit answer
    var index=0;
    countriesArray.forEach( function (value,key){
    	//text = "";
    	text+="<div class=\"col-lg-12\"><a name=\"";
    	text+=value.data;
    	text+="\"></a>";
    	text+="<h3>";
    	text+=value.data;
    	text+=": ";
    	text+=value.value;
    	text+="?";
    	text+="</h3>";
    	text+=answer[index];
    	text+="</div>";
    	index++;
    });
    content.append(text);
});